# 实验3: 矩阵

## 大纲

   - 创建矩阵
   - 矩阵的加法和减法
   - 矩阵的乘法
   - 矩阵的转置
   - 单位矩阵与逆矩阵
   - 矩阵的维度（dimension）与秩（rank）
   - 线性相关与线性无关
   - 线性变换

## 创建矩阵

矩阵的定义： 矩阵是一个二维数组，其中的每一个元素被行索引和列索引来确定。例如，下面这个矩阵 $M$ 有三行和三列：

$$
M = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

In [ ]:
import numpy as np

#从二维数组来创建numpy矩阵
M = np.array([  [1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [ ]:
# 创建一些特殊的numpy矩阵

print(np.ones((3,2)))  # 3x2的全1矩阵

print(np.zeros((3,2))) # 3x2的全0矩阵

print(np.random.random((3,2))) # 3x2的随机矩阵

print(np.diag([1, 2, 3])) # 对角矩阵

print(np.eye(3)) # 单位矩阵

### 练习3.1

- 创建一个矩阵 $A$，使得 $B$ 有两行和四列，其中的元素为 $1, 2, 3, 4, 5, 6, 7, 8$。
- 创建任意形状的全零矩阵和全一矩阵。
- 创建对角矩阵，对角线上的元素为 $2, 3, 5$。
- 创建2*2的单位矩阵。

## 矩阵的加法和减法

相同形状的矩阵可以直接相加或相减。

In [6]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f'A + B = \n {A + B} \n') # 矩阵加法
print(f'A - B = \n {A - B}') # 矩阵减法

A + B = 
 [[ 6  8]
 [10 12]] 

A - B = 
 [[-4 -4]
 [-4 -4]]


矩阵和一个标量相加或者相减，会广播到矩阵的每一个元素。

In [7]:
print(A + 1)

[[2 3]
 [4 5]]


矩阵可以和一个向量相加或者相减，然后向量会被广播到矩阵的每一行。相加时需要矩阵和向量的列数相同。

<img src="./img/2023-10-27-12-04-55.png" width="750" height="200" alt="矩阵与向量相加">

In [3]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data + np.array([1, 1]))

[[2 3]
 [4 5]
 [6 7]]


### 练习3.2

- 创建两个矩阵 $A$ 和 $B$，使得 $A$ 和 $B$ 的形状都是 $2 \times 3$，然后计算 $A + B$ 和 $A - B$。
- 计算矩阵 $A$ 和标量 $2$ 的和以及差。
- 计算矩阵 $A$ 和向量 $[1, 2, 3]$ 的和以及差。

## 矩阵的乘法

矩阵乘以一个标量,这是矩阵的数乘。

In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
print(A * 2) # 矩阵数乘

[[2 4]
 [6 8]]


矩阵的乘法：两个矩阵相乘或者一个矩阵乘以一个向量。维度必须匹配：第一个矩阵的列数必须等于第二个矩阵的行数。

![dot product](./img/2023-10-27-13-11-55.png)

In [7]:
import numpy as np

data = np.array([1, 2, 3])
powers_of_ten = np.array([[1, 10], [100, 1000], [10000, 100000]]) 

#有两种方法来调用矩阵乘法
print(data.dot(powers_of_ten))
print(data @ powers_of_ten)

[ 30201 302010]
[ 30201 302010]


## 矩阵的转置

## 单位矩阵与逆矩阵

## 矩阵的维度（dimension）与秩（rank）

## 线性相关与线性无关

## 线性变换